version: "3.4"
services:
  postgres:
    image: postgres:12
    restart: always
    networks:
      - api-server-network
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    command: -p 5430
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    restart: always
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - api-server-network

  nginx:
    image: 1.21.5-alpine
    ports:
      - "80:80"
#        - "443:443" включить если появиться https
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
      - mobile

networks:
  api-server-network:
    driver: bridge
