version: "3.4"
services:
  postgres:
    image: postgres:12
    restart: always
    networks:
      - api-server-network
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    command: -p 5430
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    restart: always
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - api-server-network
networks:
  api-server-network:
    driver: bridge