# Generated by Django 3.2.9 on 2022-01-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id_customer',
            field=models.IntegerField(null=True, verbose_name='id заказчика'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id_employee',
            field=models.IntegerField(null=True, verbose_name='Сотрудник создавший запись'),
        ),
    ]
