# Generated by Django 3.2.9 on 2022-04-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['mobile_phone'], name='mainapp_can_mobile__f6f69b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email', 'password'], name='mainapp_emp_email_249882_idx'),
        ),
    ]
