# Generated by Django 3.2.9 on 2021-12-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_customer', models.IntegerField(verbose_name='ссылка на кандидата')),
                ('users_count', models.IntegerField(verbose_name='количество приобритенных лицензий')),
                ('users_spent', models.IntegerField(verbose_name='количество потраченных лицензий')),
                ('status', models.IntegerField(verbose_name='Статус лицензии')),
                ('create_date', models.DateTimeField(verbose_name='Дата создания')),
                ('id_employee', models.IntegerField(verbose_name='Сотрудник создавший запись')),
            ],
        ),
        migrations.RemoveField(
            model_name='lnkdocumentprogram',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='lnkdocumentprogram',
            name='id_program',
        ),
        migrations.RemoveField(
            model_name='lnkgoalprogram',
            name='id_goal',
        ),
        migrations.RemoveField(
            model_name='lnkgoalprogram',
            name='id_program',
        ),
        migrations.RemoveField(
            model_name='lnkstagelevel',
            name='id_level',
        ),
        migrations.RemoveField(
            model_name='lnkstagelevel',
            name='id_stage',
        ),
        migrations.AddField(
            model_name='level',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='mainapp.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='adaptationstage',
            name='illustration',
            field=models.CharField(max_length=256, verbose_name='Ссылка на иллюстрацию'),
        ),
        migrations.AlterField(
            model_name='award',
            name='illustration',
            field=models.CharField(max_length=256, verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='block',
            name='id_stage',
            field=models.IntegerField(verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='level',
            name='illustration',
            field=models.CharField(max_length=256, verbose_name='Иллюстрация'),
        ),
        migrations.DeleteModel(
            name='LnkContactProgram',
        ),
        migrations.DeleteModel(
            name='LnkDocumentProgram',
        ),
        migrations.DeleteModel(
            name='LnkGoalProgram',
        ),
        migrations.DeleteModel(
            name='LnkStageLevel',
        ),
    ]
