# Generated by Django 3.2.9 on 2022-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220125_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='block',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='block',
            name='description',
        ),
        migrations.RemoveField(
            model_name='block',
            name='id_employee',
        ),
        migrations.RemoveField(
            model_name='block',
            name='status',
        ),
        migrations.RemoveField(
            model_name='block',
            name='tier',
        ),
        migrations.AddField(
            model_name='block',
            name='blocks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='illustration',
            field=models.ImageField(max_length=256, upload_to='', verbose_name='Иллюстрация'),
        ),
    ]
