# Generated by Django 3.2.9 on 2021-12-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211219_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='contact',
            field=models.ManyToManyField(null=True, related_name='contacts', to='mainapp.Contact', verbose_name='Контакты'),
        ),
    ]
