# Generated by Django 3.2.9 on 2022-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20220126_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationstage',
            name='illustration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка на иллюстрацию'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='illustration_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ccсылка на иллюстрацию(аватарку)'),
        ),
        migrations.AlterField(
            model_name='level',
            name='illustration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Иллюстрация'),
        ),
    ]
