# Generated by Django 3.2.9 on 2021-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_program_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='contact',
            field=models.ManyToManyField(to='mainapp.Contact', verbose_name='Контакты'),
        ),
    ]
