# Generated by Django 3.2.9 on 2022-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220201_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='illustration',
            field=models.CharField(max_length=256, verbose_name='Иллюстрация'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='illustration_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ccсылка на иллюстрацию(аватарку)'),
        ),
    ]
