# Generated by Django 3.2.9 on 2021-12-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_program_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mainapp.program', verbose_name='программа'),
        ),
        migrations.AddField(
            model_name='goal',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='mainapp.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='adaptationstage',
            name='level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='mainapp.level', verbose_name='уровень'),
        ),
        migrations.AlterField(
            model_name='block',
            name='adaptationStage',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='mainapp.adaptationstage', verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='level',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='mainapp.program', verbose_name='программа'),
        ),
    ]
