# Generated by Django 3.2.9 on 2022-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220202_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='illustration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='employee',
            name='illustration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Иллюстрация'),
        ),
        migrations.AddField(
            model_name='program',
            name='illustration',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Иллюстрация'),
        ),
    ]
