# Generated by Django 3.2.9 on 2022-02-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220202_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='blocks',
            new_name='json',
        ),
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AlterField(
            model_name='block',
            name='adaptationStage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.adaptationstage', verbose_name='Этап'),
        ),
    ]
