# Generated by Django 3.2.9 on 2021-12-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211220_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id_user_employee',
        ),
        migrations.DeleteModel(
            name='LnkLevelProgram',
        ),
    ]
