# Generated by Django 3.2.9 on 2021-12-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211226_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='mainapp.usercandidate', verbose_name='Кандидат'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='mainapp.useremployee', verbose_name='Cотрудник'),
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='password',
            field=models.CharField(default=1234, max_length=64, verbose_name='Пароль'),
        ),
    ]
