# Generated by Django 3.2.9 on 2022-02-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_document_document_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='block',
            name='adaptationStage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.adaptationstage', verbose_name='Этап'),
        ),
    ]
