# Generated by Django 3.2.9 on 2021-12-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211226_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='mainapp.usercandidate', verbose_name='Кандидат'),
        ),
    ]
