# Generated by Django 3.2.9 on 2021-12-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_candidate_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='program',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='mainapp.program', verbose_name='программа'),
        ),
    ]
