# Generated by Django 3.2.9 on 2021-12-30 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_candidate_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id_customer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 8, 35, 17, 141942), verbose_name='Дата выходa'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='salary',
            field=models.IntegerField(null=True, verbose_name='ЗП'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=64, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='program',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='mainapp.customer', verbose_name='Заказчик'),
        ),
    ]
