# Generated by Django 3.2.9 on 2021-12-30 10:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211230_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 10, 15, 19, 139409), verbose_name='Дата выходa'),
        ),
        migrations.AlterField(
            model_name='program',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='mainapp.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность адаптации'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tier',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер по порядку'),
        ),
    ]
