# Generated by Django 3.2.9 on 2021-12-30 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211230_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='customer_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_detail', to='mainapp.customer', verbose_name='Заказчик'),
        )
    ]
