# Generated by Django 3.2.9 on 2021-12-30 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20211230_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id_employee',
        ),
        migrations.AddField(
            model_name='program',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='mainapp.employee', verbose_name='Сотрудник создавший запись'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 11, 58, 36, 322520), verbose_name='Дата выходa'),
        ),
        migrations.AlterField(
            model_name='program',
            name='customer_detail',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs_detail', to='mainapp.customer', verbose_name='Заказчик'),
        ),
    ]
