# Generated by Django 3.2.9 on 2021-12-30 13:38

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211230_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='adaptationstage',
            name='duration_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность этапа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 30, 13, 37, 52, 344650), verbose_name='Дата выходa'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_link',
            field=models.URLField(verbose_name='Ccылка на файл'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='mainapp.useremployee', verbose_name='Cотрудник'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длительность адаптации'),
        ),
    ]
