# Generated by Django 3.2.9 on 2022-01-03 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20211230_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='program_details',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_details', to='mainapp.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 8, 24, 26, 813742), verbose_name='Дата выходa'),
        ),
    ]
