# Generated by Django 3.2.9 on 2022-01-03 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20220103_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='program_details',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_details', to='mainapp.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 9, 25, 31, 798792), verbose_name='Дата выходa'),
        ),
    ]
