# Generated by Django 3.2.9 on 2022-01-03 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20220103_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 11, 8, 20, 705227), verbose_name='Дата выходa'),
        ),
    ]
