# Generated by Django 3.2.9 on 2022-01-03 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_candidate_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 3, 11, 9, 53, 175290), verbose_name='Дата выходa'),
        ),
        migrations.AlterField(
            model_name='program',
            name='contact',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='program',
            name='customer',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='program',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Document', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='goals',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Goal', verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='program',
            name='levels',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Level', verbose_name='Уровни'),
        ),
    ]
