# Generated by Django 3.2.9 on 2022-01-03 11:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20220103_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='customer',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='tier',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер по порядку'),
        ),
    ]
