# Generated by Django 3.2.9 on 2022-01-04 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20220103_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationstatus',
            name='id_user_employee',
        ),
        migrations.AddField(
            model_name='adaptationstatus',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_status', to='mainapp.candidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='adaptationstatus',
            name='id_goal',
            field=models.IntegerField(null=True, verbose_name='Ссылка на выполненную цель'),
        ),
        migrations.AlterField(
            model_name='adaptationstatus',
            name='id_stage',
            field=models.IntegerField(null=True, verbose_name='Ссылка на пройденный этап'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='mainapp.usercandidate', verbose_name='Кандидат'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 5, 48, 38, 947239), verbose_name='Дата выходa'),
        ),
    ]
