# Generated by Django 3.2.9 on 2022-01-04 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20220104_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDirectory',
            fields=[
                ('directory', models.CharField(db_index=True, max_length=512, primary_key=True, serialize=False, verbose_name='Текст сообщения')),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 6, 20, 24, 121544), verbose_name='Дата выходa'),
        ),
    ]
