# Generated by Django 3.2.9 on 2022-01-04 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20220104_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDirectoryCatalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(db_index=True, max_length=512, verbose_name='Должность')),
            ],
        ),
        migrations.DeleteModel(
            name='JobDirectory',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 6, 35, 57, 719765), verbose_name='Дата выходa'),
        ),
    ]
