# Generated by Django 3.2.9 on 2022-01-04 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20220104_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 4, 6, 39, 16, 274526), verbose_name='Дата выходa'),
        ),
        migrations.AlterField(
            model_name='jobdirectorycatalogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
