# Generated by Django 3.2.9 on 2022-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20220104_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='release_date',
            field=models.DateField(verbose_name='Дата выходa'),
        ),
    ]
