# Generated by Django 3.2.9 on 2022-01-12 16:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_candidate_release_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usercandidate',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usercandidate',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='email',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='username',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='Телефон'),
        ),
    ]
